# Generated by Django 3.2.3 on 2021-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alllusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=20)),
                ('first_name1', models.CharField(max_length=20)),
                ('last_name1', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='all_users',
        ),
    ]
