# Generated by Django 3.2.3 on 2021-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210530_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=20)),
                ('last_name1', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='alllusers',
        ),
    ]
